# This file is automatically generated.
# It contains HD.RECONFIGURABLE settings for all instances of partition_def.

set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == clock_div_count || REF_NAME == clock_div_count}]
set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == clock_div_count || REF_NAME == clock_div_count}]
