set_property IOSTANDARD LVCMOS33 [get_ports {seg_activate[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_activate[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_activate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_activate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_disp[0]}]
set_property PACKAGE_PIN W4 [get_ports {seg_activate[3]}]
set_property PACKAGE_PIN V4 [get_ports {seg_activate[2]}]
set_property PACKAGE_PIN U4 [get_ports {seg_activate[1]}]
set_property PACKAGE_PIN U2 [get_ports {seg_activate[0]}]
set_property PACKAGE_PIN W7 [get_ports {seg_disp[7]}]
set_property PACKAGE_PIN W6 [get_ports {seg_disp[6]}]
set_property PACKAGE_PIN U8 [get_ports {seg_disp[5]}]
set_property PACKAGE_PIN V8 [get_ports {seg_disp[4]}]
set_property PACKAGE_PIN U5 [get_ports {seg_disp[3]}]
set_property PACKAGE_PIN V5 [get_ports {seg_disp[2]}]
set_property PACKAGE_PIN U7 [get_ports {seg_disp[1]}]
set_property PACKAGE_PIN V7 [get_ports {seg_disp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports rst]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} -add
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
