# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kanish/System_Design_through_FPGA/Vivado/Uart/uart_constraints.xdc

# IP: /home/kanish/System_Design_through_FPGA/Vivado/project_7segmentdisplayuart_updated/project_7segmentdisplayuart.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet
